"""add invite code

Revision ID: 23c8dd9cfcf7
Revises: f5d9064a4f20
Create Date: 2025-02-09 14:46:24.535555

"""

from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23c8dd9cfcf7"
down_revision: Union[str, None] = "f5d9064a4f20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rpggroup", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "invite_code",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="abc",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rpggroup", schema=None) as batch_op:
        batch_op.drop_column("invite_code")

    # ### end Alembic commands ###
