"""add cascade delete

Revision ID: f5d9064a4f20
Revises: 79b50df2294f
Create Date: 2025-02-08 13:53:58.722912

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d9064a4f20'
down_revision: Union[str, None] = '79b50df2294f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_id_name')
        batch_op.create_index(batch_op.f('ix_user_id_name'), ['id_name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id_name'))
        batch_op.create_index('ix_user_id_name', ['id_name'], unique=False)

    # ### end Alembic commands ###
