"""localized_texts are unique

Revision ID: 605de7d396d1
Revises: fc4cd0b02103
Create Date: 2025-02-13 00:41:13.545655

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605de7d396d1'
down_revision: Union[str, None] = 'fc4cd0b02103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('localizedtext', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_localizedtext_text_de'), ['text_de'], unique=False)
        batch_op.create_index(batch_op.f('ix_localizedtext_text_en'), ['text_en'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('localizedtext', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_localizedtext_text_en'))
        batch_op.drop_index(batch_op.f('ix_localizedtext_text_de'))

    # ### end Alembic commands ###
