"""add playfun questions

Revision ID: 059be63fec29
Revises: 7a83e6d44c95
Create Date: 2025-02-27 12:25:33.529822

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059be63fec29'
down_revision: Union[str, None] = '7a83e6d44c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playfunquestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('play_style', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['localizedtext.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playfunresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_rating', sa.Integer(), nullable=False),
    sa.Column('discovery_rating', sa.Integer(), nullable=False),
    sa.Column('expression_rating', sa.Integer(), nullable=False),
    sa.Column('fantasy_rating', sa.Integer(), nullable=False),
    sa.Column('fellowship_rating', sa.Integer(), nullable=False),
    sa.Column('narrative_rating', sa.Integer(), nullable=False),
    sa.Column('sensation_rating', sa.Integer(), nullable=False),
    sa.Column('submission_rating', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playfunresult')
    op.drop_table('playfunquestion')
    # ### end Alembic commands ###
