"""add userlogin

Revision ID: 7a83e6d44c95
Revises: 605de7d396d1
Create Date: 2025-02-18 21:56:02.235760

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a83e6d44c95'
down_revision: Union[str, None] = '605de7d396d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userlogin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userlogin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userlogin_account_name'), ['account_name'], unique=True)

    op.create_table('customconsententry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_sheet_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preference', sa.Enum('yes', 'okay', 'maybe', 'no', 'unknown', name='consentstatus'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['consent_sheet_id'], ['consentsheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customconsententry')
    with op.batch_alter_table('userlogin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userlogin_account_name'))

    op.drop_table('userlogin')
    # ### end Alembic commands ###
